using System;
using System.Collections.Generic;
using DataSakura.JitterPhysics.ArtifactCodec;
using DataSakura.JitterPhysics.Contracts;
using NUnit.Framework;

namespace DataSakura.JitterPhysics.Tests
{
    /// <summary>
    /// The embedded delivery path: exact bytes turned into source, and source turned back into
    /// the same bytes. Anything less than "exact" here is a level that differs between the
    /// server binary and every client.
    /// </summary>
    public sealed class EmbeddedPhysicsArtifactProviderTests
    {
        [Test]
        public void RestoresTheExactBytesThatWereEmbedded()
        {
            PhysicsArtifactPayload baked = Bake();
            EmbeddedArtifactSource source = Generate(baked);

            byte[] restored = EmbeddedPhysicsArtifactProvider.Restore(source.Chunks);

            Assert.That(restored, Is.EqualTo(baked.Bytes));
            Assert.That(JitterPhysicsHash.Sha256Hex(restored), Is.EqualTo(baked.ArtifactHash));
        }

        [Test]
        public void LoadsTheArtifactFromTheEmbeddedChunks()
        {
            PhysicsArtifactPayload baked = Bake();
            EmbeddedArtifactSource source = Generate(baked);

            var provider = new EmbeddedPhysicsArtifactProvider(
                source.Chunks,
                PhysicsArtifactManifestCodec.Write(baked.Manifest),
                "embedded:test");

            PhysicsArtifactLoadResult result = provider.Load(baked.Manifest.RuntimeCompatibilityId);

            Assert.That(result.Succeeded, Is.True, result.Error.ToString());
            Assert.That(result.Artifact.LevelId, Is.EqualTo("arena"));
            Assert.That(result.ArtifactHash, Is.EqualTo(baked.ArtifactHash));
            Assert.That(result.Source, Is.EqualTo("embedded:test"));
        }

        [Test]
        public void GeneratesIdenticalSourceForTheSameArtifact()
        {
            PhysicsArtifactPayload baked = Bake();

            Assert.That(Generate(baked).Code, Is.EqualTo(Generate(baked).Code));
        }

        [Test]
        public void GeneratedSourceCarriesTheIdentityAndNoTimestamp()
        {
            PhysicsArtifactPayload baked = Bake();

            string code = Generate(baked).Code;

            Assert.That(code, Does.Contain("public const string LevelId = \"arena\";"));
            Assert.That(code, Does.Contain("public const string ArtifactHash = \"" + baked.ArtifactHash + "\";"));
            Assert.That(code, Does.Contain("namespace Consumer.Server.Generated"));
            Assert.That(code, Does.Contain("<auto-generated>"));

            // A timestamp would make two exports of one artifact look like a change, which is
            // how a generated file stops being reviewed.
            Assert.That(code, Does.Not.Contain(DateTime.UtcNow.Year.ToString()));
        }

        [Test]
        public void SplitsThePayloadIntoAlignedChunks()
        {
            PhysicsArtifactPayload baked = Bake();
            var options = new EmbeddedArtifactSourceOptions(
                "Consumer.Server.Generated", "ArenaArtifact", chunkLength: 64);

            EmbeddedArtifactSource source = EmbeddedArtifactSourceGenerator.Generate(
                baked.Bytes, baked.Manifest, options);

            Assert.That(source.Chunks.Count, Is.GreaterThan(1));
            for (int i = 0; i < source.Chunks.Count - 1; i++)
            {
                Assert.That(source.Chunks[i].Length, Is.EqualTo(64));
            }

            Assert.That(EmbeddedPhysicsArtifactProvider.Restore(source.Chunks), Is.EqualTo(baked.Bytes));
        }

        [Test]
        public void RefusesAPayloadOverTheEmbeddingCap()
        {
            PhysicsArtifactPayload baked = Bake();
            var options = new EmbeddedArtifactSourceOptions(
                "Consumer.Server.Generated", "ArenaArtifact", maxEmbeddedBytes: 16);

            Assert.That(
                () => EmbeddedArtifactSourceGenerator.Generate(baked.Bytes, baked.Manifest, options),
                Throws.ArgumentException.With.Message.Contains("cap"));
        }

        [Test]
        public void RefusesBytesAndAManifestThatDoNotBelongTogether()
        {
            PhysicsArtifactPayload baked = Bake();
            var foreign = new PhysicsArtifactManifest(
                baked.Manifest.SchemaVersion,
                baked.Manifest.RuntimeCompatibilityId,
                baked.Manifest.GeneratorVersion,
                baked.Manifest.LevelId,
                JitterPhysicsHash.Sha256HexUtf8("some other artifact"),
                baked.Manifest.BodyCount,
                baked.Manifest.ShapeCount,
                baked.Manifest.VertexCount,
                baked.Manifest.TriangleCount,
                baked.Manifest.TickRate,
                baked.Manifest.FileName);

            Assert.That(
                () => EmbeddedArtifactSourceGenerator.Generate(baked.Bytes, foreign, Options()),
                Throws.ArgumentException);
        }

        [Test]
        public void RejectsChunksThatWereEditedByHand()
        {
            PhysicsArtifactPayload baked = Bake();
            EmbeddedArtifactSource source = Generate(baked);

            var edited = new List<string>(source.Chunks);
            edited[0] = "A" + edited[0].Substring(1);

            PhysicsArtifactLoadResult result = new EmbeddedPhysicsArtifactProvider(
                edited, PhysicsArtifactManifestCodec.Write(baked.Manifest)).Load(null);

            Assert.That(result.Succeeded, Is.False);

            // Which of the two fires depends on where the edited chunk landed: a flipped byte
            // in the header fails the magic check, anywhere else fails the hash. Both are the
            // same statement — hand-edited generated bytes are not the artifact that was baked.
            Assert.That(
                result.Error.Code,
                Is.EqualTo(PhysicsArtifactErrorCode.HashMismatch)
                    .Or.EqualTo(PhysicsArtifactErrorCode.BadMagic));
        }

        [Test]
        public void RejectsAManifestThatIsNotAManifest()
        {
            PhysicsArtifactPayload baked = Bake();
            EmbeddedArtifactSource source = Generate(baked);

            PhysicsArtifactLoadResult result =
                new EmbeddedPhysicsArtifactProvider(source.Chunks, "not json").Load(null);

            Assert.That(result.Succeeded, Is.False);
            Assert.That(result.Error.Code, Is.EqualTo(PhysicsArtifactErrorCode.ManifestMismatch));
        }

        [Test]
        public void RefusesANamespaceThatWouldNotCompile()
        {
            Assert.That(
                () => new EmbeddedArtifactSourceOptions("2 bad namespace", "ArenaArtifact"),
                Throws.ArgumentException);

            Assert.That(
                () => new EmbeddedArtifactSourceOptions("Consumer.Server", "class"),
                Throws.Nothing,
                "keywords are the consumer's problem; only shape is checked here");

            Assert.That(
                () => new EmbeddedArtifactSourceOptions("Consumer.Server", "Arena", chunkLength: 10),
                Throws.ArgumentException,
                "unaligned chunks would break base64 decoding");
        }

        private static EmbeddedArtifactSourceOptions Options()
        {
            return new EmbeddedArtifactSourceOptions("Consumer.Server.Generated", "ArenaArtifact");
        }

        private static EmbeddedArtifactSource Generate(PhysicsArtifactPayload baked)
        {
            return EmbeddedArtifactSourceGenerator.Generate(baked.Bytes, baked.Manifest, Options());
        }

        private static PhysicsArtifactPayload Bake()
        {
            var body = new PhysicsBodyRecord(
                "ground",
                PhysicsVector3.Zero,
                PhysicsQuaternion.Identity,
                0.2f,
                0f,
                new List<PhysicsShapeRecord>
                {
                    PhysicsShapeRecord.Box(
                        "shape_00",
                        PhysicsVector3.Zero,
                        PhysicsQuaternion.Identity,
                        new PhysicsVector3(30f, 1f, 30f)),
                    PhysicsShapeRecord.Mesh(
                        "shape_01",
                        PhysicsVector3.Zero,
                        PhysicsQuaternion.Identity,
                        new[]
                        {
                            new PhysicsVector3(0f, 0f, 0f),
                            new PhysicsVector3(4f, 0f, 0f),
                            new PhysicsVector3(0f, 4f, 0f),
                        },
                        new[] { 0, 1, 2 }),
                });

            var artifact = new PhysicsArtifact(
                JitterPhysicsPackage.ArtifactSchemaVersion,
                JitterPhysicsHash.Sha256HexUtf8("embedded-runtime"),
                "arena",
                PhysicsWorldSettings.Default,
                new List<PhysicsBodyRecord> { body });

            return PhysicsArtifactWriter.WriteWithManifest(artifact, JitterPhysicsPackage.PackageVersion);
        }
    }
}



